// Generated by CoffeeScript 1.7.1
(function() {
  var fs, path, write, _;

  fs = require("fs");

  path = require("path");

  _ = require("underscore");

  write = function(filePath) {
    var config, e, outputPath, schemas;
    config = require(filePath);
    schemas = config.files;
    outputPath = "" + __dirname + "/../docs/api.md";
    try {
      if (fs.existsSync(outputPath)) {
        fs.unlinkSync(outputPath);
      }
    } catch (_error) {
      e = _error;
      console.log(e, 'lol');
    }
    return schemas.forEach(function(schema) {
      schema = require("" + __dirname + "/../" + schema);
      try {
        return fs.appendFileSync(outputPath, _.template(fs.readFileSync("" + __dirname + "/templates/md.tpl").toString())({
          schema: schema
        }));
      } catch (_error) {
        e = _error;
        return console.log(e, 'lol');
      }
    });
  };

  module.exports = {
    write: write
  };

}).call(this);
